### ISSUE TITLE
Doesn`t build under NR 1.0.3

### ISSUE THREAD

**Issue by amizer12** [hadifikri/node-red-contrib-oled-sh1106#1]
Hi !
Thanks so much for this as i've been trying to get this oled working for some time and its nice somebody skilled enough created a node for it !
But the issue is that it doens't buld for me under 1.0.3 and NodeJS - 12.14.0- can you verify if the code is ok as i'm not sure if it's something at my end or not.
Thanks again !

**Comment by amizer12** [comment]
Downgraing to Node 10.X fixes the issue  :)

**Comment by hadifikri** [comment]
Forgot to mentioned it in the readme, as of now, the node-red recommendation is node.js version 10. So we'll stick with it for now.
